package com.telecom.billing.telecom_billing.Models;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/*
============================================
= CUSTOMER ENTITY — EXPLANATION NOTES
============================================

• @Entity → Marks this class as a JPA entity mapped to the "customer" table.

• Inherits createdAt & updatedAt from BaseEntity (auto-handled timestamps).

• @Id + @GeneratedValue(IDENTITY)
     → Primary key auto-generated by PostgreSQL.

• @Column(nullable=false, unique=true)
     → DB-level constraints for required fields & uniqueness.

• @ManyToOne(fetch = LAZY) plan
     → Many customers share one plan.
     → Lazy loading improves performance.
     → @JsonBackReference prevents infinite JSON recursion
        (Customer → Plan → Customer → ...).

• @JoinColumn(name="plan_id", nullable=false)
     → Adds a foreign key column plan_id in customer table.

• @OneToMany(mappedBy="customer") usages & invoices
     → One customer can have many usage/invoice rows.
     → "mappedBy" means Usage/Invoice owns the foreign key.
     → @JsonManagedReference allows serialization of child list
        while preventing recursion back to customer.

• @OneToOne(fetch = LAZY) user
     → Each customer can be linked to exactly one user account.
     → Stored via "user_id" FK in the customer table (unique=true).
     → @JsonIgnore prevents exposing authentication data
        in API responses.

• JSON Recursion Handling:
     @JsonManagedReference → parent side (shown in JSON)
     @JsonBackReference    → child side (hidden in JSON)
     Prevents circular serialization errors.

• Best Practice Note:
     Returning entities directly from controllers can expose unwanted
     fields or cause lazy-loading issues.
     DTOs (Data Transfer Objects) are recommended for APIs.
*/




/*
 * @JsonManagedReference / @JsonBackReference Explanation:
 *
 * - These annotations prevent infinite JSON recursion in bidirectional relationships.
 *
 *   Customer (parent)
 *      ↳ usages (child)
 *      ↳ invoices (child)
 *
 *   Usage/Invoice has: @JsonBackReference
 *   Customer has:      @JsonManagedReference
 *
 * - Result:
 *      Customer → includes usages/invoices
 *      Usage/Invoice → does NOT include customer again
 *
 * - Avoids: Customer → Usage → Customer → Usage → ... (infinite loop)
 */



/*
 * One-to-One link between Customer and User:
 *
 * - customer.user_id holds FK → user.id
 * - unique=true ensures true 1:1 relationship (no two customers share a user)
 * - LAZY loading means user is not fetched unless needed
 * - @JsonIgnore avoids returning sensitive user info (password, roles) in API
 *
 * This lets customers log in while keeping user credentials hidden from responses.
 */


@Entity
@Getter 
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Customer extends BaseEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 100)
    private String name;

    @Column(unique = true, nullable = false, length = 150)
    private String email;

    @Column(unique = true, nullable = false, length = 20)
    private String phoneNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JsonBackReference
    
    @JoinColumn(name = "plan_id", nullable = false)
    private Plan plan;

    @OneToMany(mappedBy = "customer")
    @JsonManagedReference
    

    private List<Usage> usages = new ArrayList<>();

    @OneToMany(mappedBy = "customer")
    @JsonManagedReference
    private List<Invoice> invoices = new ArrayList<>();

    // Link to a User account (nullable for pre-provisioned customers)
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", unique = true)
    @JsonIgnore  // do not serialize user inside customer responses (avoid exposing auth fields)
    private User user;




}
