package com.telecom.billing.telecom_billing.Models;

import java.util.ArrayList;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/*
=============================================
= PLAN ENTITY — EXPLANATION NOTES
=============================================

• @Entity  
     Marks this class as a JPA entity mapped to the "plan" table.

• Extends BaseEntity  
     Inherits createdAt and updatedAt timestamps.

• @Id + @GeneratedValue(IDENTITY)  
     Auto-increment primary key generated by PostgreSQL.

• code (unique)  
     Unique plan code such as POSTPAID100, UNLIMITED399, etc.

• name  
     Human-friendly name of the plan (e.g., "Postpaid 100").

• ratePerMinute, ratePerGB, ratePerSMS  
     Pricing values used during invoice calculation.

• @OneToMany(mappedBy = "plan") customers  
     A plan can have multiple customers.  
     "mappedBy = plan" means the foreign key is in Customer table.  
     @JsonManagedReference prevents JSON recursion with Customer.

• toString()  
     Clean readable output for debugging/logs.
*/


@Entity
@Getter
@Setter
@NoArgsConstructor 
@AllArgsConstructor
public class Plan extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false, length = 50)
    private String code;

    @Column(nullable = false, length = 100)
    private String name;

    @Column(nullable = false)
    private double ratePerMinute;

    @Column(nullable = false)
    private double ratePerGB;

    @Column(nullable = false)
    private double ratePerSMS;

    @OneToMany(mappedBy = "plan")
    @JsonManagedReference
    

    private List<Customer> customers = new ArrayList<>();
    
    @Override
    public String toString() {
        return "Plan{" +
                "id=" + id +
                ", code='" + code + '\'' +
                ", name='" + name + '\'' +
                ", ratePerMinute=" + ratePerMinute +
                ", ratePerGB=" + ratePerGB +
                ", ratePerSMS=" + ratePerSMS +
                '}';
    }

}

